const Options = [
"Ugly sweater",
"two drinks at once",
"spills a drink",
"\“Christmas is cancelled\”",
"festivus reference",
"llamas",
"drinking eggnog",
"wearing a santa hat",
"mentions Bracco",
"Inappropriate comment to Brian",
"silos",
"movie quote",
"shots",
"awkward moment",
"singing",
"pet story",
"showing pictures on phone",
"balls joke",
"bad",
"pun",
"man bun",
"speech",
"hugs",
"trip/fall",
"inappropriate attire",
"creepy",
"someone disappears",
"dancing",
"wardrobe malfunction",
"mentions Gretchen retiring",
"Tim does something weird"
]

export default Options;
